name: Enforce Branch Naming

on:
  create:
    branches:
      - "*"

jobs:
  enforce-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch Name
        run: |
          BRANCH_NAME=$(git branch --show-current)
          if [[ ! "$BRANCH_NAME" =~ ^feature/.*$ ]]; then
            echo "Error: Branch name doesn't follow the 'feature/*' format."
            # You can choose to rename or delete the branch here.
            # Example: git branch -m feature/$BRANCH_NAME
            exit 1
          fi
