name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*' # Match all feature branches

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: pid-ui
        run: npm install

      - name: Build frontend
        working-directory: pid-ui
        run: npm run build

      - name: Deploy frontend
        if: github.ref == 'refs/heads/main' # Deploy only from main branch
        working-directory: pid-ui
        run: |
          # Deployment steps for production environment (main branch)
          # Replace with your deployment commands.

      - name: Deploy frontend to staging
        if: github.ref == 'refs/heads/develop' # Deploy from develop branch
        working-directory: pid-ui
        run: |
          # Deployment steps for staging environment (develop branch)
          # Replace with your deployment commands.

      - name: Deploy frontend to feature branch preview
        if: startsWith(github.ref, 'refs/heads/feature/') # Deploy from feature branches
        working-directory: pid-ui
        run: |
          # Deployment steps for feature branch preview environments
          # Replace with your deployment commands.

  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        working-directory: pid-be
        run: pip install -r requirements.txt

      - name: Run backend tests
        working-directory: pid-be
        run: pytest
