name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - develop

jobs:
    build-and-deploy-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.6.1

            - name: Install dependencies
              working-directory: pid-ui
              run: npm install

            - name: Build frontend
              working-directory: pid-ui
              run: npm run build

            - name: Deploy frontend to production
              if: github.ref == 'refs/heads/main' # Deploy only from main branch
              working-directory: pid-ui
              run: |
                  # Deployment steps for production environment (main branch)
                  # Replace with your deployment commands.

            - name: Deploy frontend to pre-production
              if: github.ref == 'refs/heads/main' # Deploy only from main branch
              working-directory: pid-ui
              run: |
                  # Deployment steps for production environment (main branch)
                  # Replace with your deployment commands.

            - name: Deploy frontend to staging
              if: github.ref == 'refs/heads/develop' # Deploy from develop branch
              working-directory: pid-ui
              run: |
                  # Deployment steps for staging environment (develop branch)
                  # Replace with your deployment commands.

    test-backend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.x

            - name: Install Poetry
              working-directory: pid-be
              run: pip install poetry

            - name: Build backend
              working-directory: pid-be
              run: poetry init

            - name: Install firebase
              working-directory: pid-be
              run: npm install -g firebase-tools

            - name: Run emualtors
              working-directory: pid-be
              run: "firebase emulators:start &"

            - name: Run Backend
              working-directory: pid-be
              run: poetry run start &

            - name: Run Backend Tests
              env:
                  PROJECT_ID: ${{ secrets.PROJECT_ID }}
                  PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                  CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  AUTH_URI: ${{ secrets.AUTH_URI }}
                  TOKEN_URI: ${{ secrets.TOKEN_URI }}
                  AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.AUTH_PROVIDER_X509_CERT_URL }}
                  CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
                  UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
              working-directory: pid-be
              run: poetry run pytest .\tests\
